
name: koodo-reader-docker镜像打包

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: git clone -b master https://github.com/koodo-reader/koodo-reader.git
      - run: cd koodo-reader
      - run: docker-compose up -f ./docker-compose.yml -d

